name: Publish latest

on:
  schedule:
    - cron: '0 6 * * *'
  push:
    branches: ['main']

jobs:
  build-push:
    uses: './.github/workflows/push-build.action.yml'
    secrets: inherit
    with:
      architectures: |
        linux/amd64
      tag: latest

  build-push-dev:
    uses: './.github/workflows/push-build.action.yml'
    secrets: inherit
    with:
      architectures: |
        linux/amd64
      tag: dev

  build-push-nightly:
    uses: './.github/workflows/push-build.action.yml'
    secrets: inherit
    with:
      architectures: |
        linux/amd64
        linux/arm64
      tag: nightly
