name: Build base workflow

on:
  workflow_call:
    inputs:
      architectures:
        description: 'The architectures to build for'
        required: true
        type: string
      tag:
        description: 'The docker tag for the image'
        type: string
        default: 'latest'
    secrets:
      DOCKER_USERNAME:
        description: 'Docker Hub username'
        required: true
      DOCKER_PASSWORD:
        description: 'Docker Hub password'
        required: true

jobs:
  build-job:
    name: Build ${{ github.ref_name }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: mvanduijker/viewtube-all-in-one
          tags: |
            type=raw,value=${{ inputs.tag }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ inputs.architectures }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
